export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';
export const GET_USER_SUBMITTED = 'GET_USER_SUBMITTED';
export const UNLOAD_REDDIT_USER_COMMENTS = 'UNLOAD_REDDIT_USER_COMMENTS';
export const UNLOAD_REDDIT_USER_SUBMISSIONS = 'UNLOAD_REDDIT_USER_SUBMISSIONS';