// Reddit API action constants
export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';
export const GET_USER_SUBMITTED = 'GET_USER_SUBMITTED';
export const UNLOAD_REDDIT_USER_COMMENTS = 'UNLOAD_REDDIT_USER_COMMENTS';
export const UNLOAD_REDDIT_USER_SUBMISSIONS = 'UNLOAD_REDDIT_USER_SUBMISSIONS';

// GitHub API action constants
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_REPOS = 'GET_USER_REPOS';
export const UNLOAD_USER_INFO = 'UNLOAD_USER_INFO';